name: crypto_coins_list
description: Cool crypto application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  intl: ^0.19.0
  talker_flutter: ^2.4.3
  talker_dio_logger: ^1.3.0
  talker_bloc_logger: ^1.1.0
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
